stages:
  - ops_test
  - ops_benchmark

ops_test:
  stage: ops_test
  only:
    - master
  script:
    - FAILURE_PATTERN="FAILED\|Aborted\|Inappropriate ioctl for device" tools/bazel-adb-run.sh //mace/ops:ops_test

ops_benchmark:
  stage: ops_benchmark
  only:
    - master
  script:
    - FAILURE_PATTERN="Aborted\|Inappropriate ioctl for device" tools/bazel-adb-run.sh //mace/ops:ops_benchmark
